force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/OCIInteractionFulfillOrderItem__c.object-meta.xml
<CustomObject>
    <label>OCI Interaction Fulfill Order Item</label>
    <nameField>
        <displayFormat>OCI-FI-{0000}</displayFormat>
        <label>OCIInteractionFulfillOrderItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCI Interaction Fulfill Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/fields/FulfillmentOrderItem__c.field-meta.xml
<CustomField>
    <fullName>FulfillmentOrderItem__c</fullName>
    <label>Fulfillment Order Product</label>
    <referenceTo>FulfillmentOrderLineItem</referenceTo>
    <relationshipLabel>OCI Interaction Fulfill Order Items</relationshipLabel>
    <relationshipName>OCIInteractionFulfillOrderItems</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/fields/Main_Fulfillment_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Main_Fulfillment_Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Fulfillment Order Product</label>
    <referenceTo>FulfillmentOrderLineItem</referenceTo>
    <relationshipLabel>OCI Interaction Fulfill Order Items (Main Fulfillment Order Item)</relationshipLabel>
    <relationshipName>OCI_Interaction_Fulfill_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/classes/OCIInteractionFOBundleAction.cls
public with sharing class OCIInteractionFOBundleAction {
    public OCIInteractionFOBundleAction() {

    }

    @InvocableMethod(label='Get OCI Interaction Fulfill Order Item with inventory' description='Filters and returns OCI Interaction Fulfill Order Item with inventory' category='Order Management')
    public static List<OCIInteractionFOBundleActionOutput> getRecordWithInventory(List<OCIInteractionFOBundleActionInput> inputs){
        List<OCIInteractionFOBundleActionOutput> result = new List<OCIInteractionFOBundleActionOutput>();

        for (OCIInteractionFOBundleActionInput input : inputs) {

            OCIInteractionFOBundleActionOutput output = new OCIInteractionFOBundleActionOutput();

            Set<String> parentsWithoutInventory = new Set<String>();
            
            List<OCIInteractionFulfillOrderItem__c> remainingItemsToProcess = new List<OCIInteractionFulfillOrderItem__c>();
            
            //detect children with inventory
            for(OCIInteractionFulfillOrderItem__c item: input.OCIInteractionFulfillOrderItems){
                if(item.Main_Fulfillment_Order_Item__c != null){
                    if(item.Associated_Item_Inventory__c == 'NotIncludedInMainInventory'){
                        //add to response since this child has inventory
                        output.OCIInteractionFulfillOrderItems.add(item);
                        
                        //we want to exlude the parent later on, because it doesnt have inventory
                        if(!parentsWithoutInventory.contains(item.Main_Fulfillment_Order_Item__c)){
                            parentsWithoutInventory.add(item.Main_Fulfillment_Order_Item__c);
                        }
                    }
                }else{
                    //other items we process in another loop, because we need to know all the parents withut inventory first
                    remainingItemsToProcess.add(item);
                }
            }

            if(parentsWithoutInventory.size() == 0){
                output.OCIInteractionFulfillOrderItems.addAll(remainingItemsToProcess);
            }else{
                //loop suspset of records that have regular products (non bundles) and parents
                for(OCIInteractionFulfillOrderItem__c item: remainingItemsToProcess){
                    if(!parentsWithoutInventory.contains(item.FulfillmentOrderItem__c)){
                        output.OCIInteractionFulfillOrderItems.add(item);
                    }
                }
            }
            
            result.add(output);

        }

        return result;
    }
}