force-app/main/default/objects/OCIInteractionFulfillOrder__c/OCIInteractionFulfillOrder__c.object-meta.xml
<CustomObject>
    <label>OCI Interaction Fulfill Order</label>
    <nameField>
        <displayFormat>OCI-F-{0000}</displayFormat>
        <label>IASInteractionFulfillOrder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCI Interaction Fulfill Order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OCIInteractionFulfillOrder__c/fields/ConnectionFailedAttempts__c.field-meta.xml
<CustomField>
    <fullName>ConnectionFailedAttempts__c</fullName>
    <label>Connection Failed Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrder__c/fields/FulfillmentOrder__c.field-meta.xml
<CustomField>
    <fullName>FulfillmentOrder__c</fullName>
    <label>Fulfillment Order</label>
    <referenceTo>FulfillmentOrder</referenceTo>
    <relationshipLabel>OCI Interaction Fulfill Orders</relationshipLabel>
    <relationshipName>OCIInteractionFulfillOrders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrder__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABANDONED</fullName>
            </value>
            <value>
                <fullName>COMPLETED_FAIL</fullName>
            </value>
            <value>
                <fullName>COMPLETED_SUCCEED</fullName>
            </value>
            <value>
                <fullName>REQUESTED</fullName>
                <default>true</default>
                <label>REQUESTED</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrder__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TRANSFER_MOVE</fullName>
            </value>
            <value>
                <fullName>TRANSFER_CANCEL</fullName>
            </value>
            <value>
                <fullName>FULFILLMENT</fullName>
                <default>true</default>
                <label>FULFILLMENT</label>
            </value>
            <value>
                <fullName>TRANSFER_RELEASE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/OCIInteractionFulfillOrderItem__c.object-meta.xml
<CustomObject>
    <label>OCI Interaction Fulfill Order Item</label>
    <nameField>
        <displayFormat>OCI-FI-{0000}</displayFormat>
        <label>OCIInteractionFulfillOrderItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCI Interaction Fulfill Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/fields/FulfillmentOrderItem__c.field-meta.xml
<CustomField>
    <fullName>FulfillmentOrderItem__c</fullName>
    <label>Fulfillment Order Product</label>
    <referenceTo>FulfillmentOrderLineItem</referenceTo>
    <relationshipLabel>OCI Interaction Fulfill Order Items</relationshipLabel>
    <relationshipName>OCIInteractionFulfillOrderItems</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/fields/Main_Fulfillment_Order_Item__c.field-meta.xml
<CustomField>
    <fullName>Main_Fulfillment_Order_Item__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Fulfillment Order Product</label>
    <referenceTo>FulfillmentOrderLineItem</referenceTo>
    <relationshipLabel>OCI Interaction Fulfill Order Items (Main Fulfillment Order Item)</relationshipLabel>
    <relationshipName>OCI_Interaction_Fulfill_Order_Items</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/fields/OCIInteractionFulfillOrder__c.field-meta.xml
<CustomField>
    <fullName>OCIInteractionFulfillOrder__c</fullName>
    <label>OCI Interaction Fulfill Order</label>
    <referenceTo>OCIInteractionFulfillOrder__c</referenceTo>
    <relationshipLabel>OCI Interaction Fulfill Order Items</relationshipLabel>
    <relationshipName>OCIInteractionFulfillOrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REQUESTED</fullName>
                <default>true</default>
                <label>REQUESTED</label>
            </value>
            <value>
                <fullName>COMPLETED_SUCCEED</fullName>
            </value>
            <value>
                <fullName>COMPLETED_FAIL</fullName>
            </value>
            <value>
                <fullName>ABANDONED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/OCIInteractionFOBundleActionTest.cls
@isTest
private class OCIInteractionFOBundleActionTest {

    @isTest
    static void testFilteringBundleInventoryAllRegularProducts() {
        // Create Records
        FulfillmentOrder fo = seedFulfillOrder();
        FulfillmentOrderLineItem foli1 = seedFulfillOrderLineItem(fo);
        FulfillmentOrderLineItem foli2 = seedFulfillOrderLineItem(fo);
        FulfillmentOrderLineItem foli3 = seedFulfillOrderLineItem(fo);
        FulfillmentOrderLineItem foli4 = seedFulfillOrderLineItem(fo);
        
        OCIInteractionFulfillOrder__c ociFulfill = seedOCIFullfillOrder(fo);
        
        OCIInteractionFulfillOrderItem__c ociFulfillItem1 = seedOCIFullfillOrderItem(ociFulfill, foli1, null, null);
        OCIInteractionFulfillOrderItem__c ociFulfillItem2 = seedOCIFullfillOrderItem(ociFulfill, foli2, null, null);
        OCIInteractionFulfillOrderItem__c ociFulfillItem3 = seedOCIFullfillOrderItem(ociFulfill, foli3, null, null);
        OCIInteractionFulfillOrderItem__c ociFulfillItem4 = seedOCIFullfillOrderItem(ociFulfill, foli4, null, null);
        
        List<OCIInteractionFOBundleActionInput> inputs = new List<OCIInteractionFOBundleActionInput>();
        OCIInteractionFOBundleActionInput input1 = new OCIInteractionFOBundleActionInput();
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem1);
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem2);
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem3);
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem4);

        inputs.add(input1);
        List<OCIInteractionFOBundleActionOutput> outputs = OCIInteractionFOBundleAction.getRecordWithInventory(inputs);

        System.assertEquals(1, outputs.size());
        System.assertEquals(4, outputs.get(0).OCIInteractionFulfillOrderItems.size());
    }

    @isTest
    static void testFilteringBundleInventoryAtChildren() {
        // Create Records
        FulfillmentOrder fo = seedFulfillOrder();
        FulfillmentOrderLineItem foli1 = seedFulfillOrderLineItem(fo);
        FulfillmentOrderLineItem foli2 = seedFulfillOrderLineItem(fo);
        FulfillmentOrderLineItem foli3 = seedFulfillOrderLineItem(fo);
        FulfillmentOrderLineItem foli4 = seedFulfillOrderLineItem(fo);
        
        OCIInteractionFulfillOrder__c ociFulfill = seedOCIFullfillOrder(fo);
        
        OCIInteractionFulfillOrderItem__c ociFulfillItem1 = seedOCIFullfillOrderItem(ociFulfill, foli1, null, null);
        OCIInteractionFulfillOrderItem__c ociFulfillItem2 = seedOCIFullfillOrderItem(ociFulfill, foli2, null, null);
        //children
        OCIInteractionFulfillOrderItem__c ociFulfillItem3 = seedOCIFullfillOrderItem(ociFulfill, foli3, foli1.Id, 'NotIncludedInMainInventory');
        OCIInteractionFulfillOrderItem__c ociFulfillItem4 = seedOCIFullfillOrderItem(ociFulfill, foli4, foli1.Id, 'NotIncludedInMainInventory');
        
        List<OCIInteractionFOBundleActionInput> inputs = new List<OCIInteractionFOBundleActionInput>();
        OCIInteractionFOBundleActionInput input1 = new OCIInteractionFOBundleActionInput();
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem1);
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem2);
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem3);
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem4);

        inputs.add(input1);
        List<OCIInteractionFOBundleActionOutput> outputs = OCIInteractionFOBundleAction.getRecordWithInventory(inputs);

        System.assertEquals(3, outputs.get(0).OCIInteractionFulfillOrderItems.size());

        for(OCIInteractionFulfillOrderItem__c item: outputs.get(0).OCIInteractionFulfillOrderItems){
            //make sure parent is not in the output since it doesn't have iventory
            System.assertNotEquals(ociFulfillItem1.Id, item.Id);
        }
    }

    @isTest
    static void testFilteringBundleInventoryAtParent() {
        // Create Records
        FulfillmentOrder fo = seedFulfillOrder();
        FulfillmentOrderLineItem foli1 = seedFulfillOrderLineItem(fo);
        FulfillmentOrderLineItem foli2 = seedFulfillOrderLineItem(fo);
        FulfillmentOrderLineItem foli3 = seedFulfillOrderLineItem(fo);
        FulfillmentOrderLineItem foli4 = seedFulfillOrderLineItem(fo);
        
        OCIInteractionFulfillOrder__c ociFulfill = seedOCIFullfillOrder(fo);
        
        OCIInteractionFulfillOrderItem__c ociFulfillItem1 = seedOCIFullfillOrderItem(ociFulfill, foli1, null, null);
        OCIInteractionFulfillOrderItem__c ociFulfillItem2 = seedOCIFullfillOrderItem(ociFulfill, foli2, null, null);
        //children
        OCIInteractionFulfillOrderItem__c ociFulfillItem3 = seedOCIFullfillOrderItem(ociFulfill, foli3, foli1.Id, 'IncludedInMainInventory');
        OCIInteractionFulfillOrderItem__c ociFulfillItem4 = seedOCIFullfillOrderItem(ociFulfill, foli4, foli1.Id, 'IncludedInMainInventory');
        
        List<OCIInteractionFOBundleActionInput> inputs = new List<OCIInteractionFOBundleActionInput>();
        OCIInteractionFOBundleActionInput input1 = new OCIInteractionFOBundleActionInput();
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem1);
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem2);
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem3);
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem4);

        inputs.add(input1);
        List<OCIInteractionFOBundleActionOutput> outputs = OCIInteractionFOBundleAction.getRecordWithInventory(inputs);

        System.assertEquals(2, outputs.get(0).OCIInteractionFulfillOrderItems.size());

        for(OCIInteractionFulfillOrderItem__c item: outputs.get(0).OCIInteractionFulfillOrderItems){
            //make sure children are not in the output since those do not track iventory
            System.assertNotEquals(ociFulfillItem3.Id, item.Id);
            System.assertNotEquals(ociFulfillItem4.Id, item.Id);
        }
    }

    @isTest
    static void testFilteringBundleInventoryAtParentAndNullStockCheckMethod() {
        // Create Records
        FulfillmentOrder fo = seedFulfillOrder();
        FulfillmentOrderLineItem foli1 = seedFulfillOrderLineItem(fo);
        FulfillmentOrderLineItem foli2 = seedFulfillOrderLineItem(fo);
        FulfillmentOrderLineItem foli3 = seedFulfillOrderLineItem(fo);
        FulfillmentOrderLineItem foli4 = seedFulfillOrderLineItem(fo);
        
        OCIInteractionFulfillOrder__c ociFulfill = seedOCIFullfillOrder(fo);
        
        OCIInteractionFulfillOrderItem__c ociFulfillItem1 = seedOCIFullfillOrderItem(ociFulfill, foli1, null, null);
        OCIInteractionFulfillOrderItem__c ociFulfillItem2 = seedOCIFullfillOrderItem(ociFulfill, foli2, null, null);
        //children
        OCIInteractionFulfillOrderItem__c ociFulfillItem3 = seedOCIFullfillOrderItem(ociFulfill, foli3, foli1.Id, null);
        OCIInteractionFulfillOrderItem__c ociFulfillItem4 = seedOCIFullfillOrderItem(ociFulfill, foli4, foli1.Id, null);
        
        List<OCIInteractionFOBundleActionInput> inputs = new List<OCIInteractionFOBundleActionInput>();
        OCIInteractionFOBundleActionInput input1 = new OCIInteractionFOBundleActionInput();
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem1);
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem2);
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem3);
        input1.OCIInteractionFulfillOrderItems.add(ociFulfillItem4);

        inputs.add(input1);
        List<OCIInteractionFOBundleActionOutput> outputs = OCIInteractionFOBundleAction.getRecordWithInventory(inputs);

        System.assertEquals(2, outputs.get(0).OCIInteractionFulfillOrderItems.size());

        for(OCIInteractionFulfillOrderItem__c item: outputs.get(0).OCIInteractionFulfillOrderItems){
            //make sure children are not in the output since those do not track iventory
            System.assertNotEquals(ociFulfillItem3.Id, item.Id);
            System.assertNotEquals(ociFulfillItem4.Id, item.Id);
        }
    }

    // Create Fulfillment Order
    private static FulfillmentOrder seedFulfillOrder(){
        OrderDeliveryMethod odm = new OrderDeliveryMethod(
                                        IsActive = false,
                                        Name = 'test'
                                    );
        insert odm;
        FulfillmentOrder fo = new FulfillmentOrder(
                                    status = 'Draft',
                                    FulfilledToName = 'test',
                                    DeliveryMethodId = odm.Id
                                );
        insert fo;
        return fo;
    }

    // Create Fulfillment Order Line Item
    private static FulfillmentOrderLineItem seedFulfillOrderLineItem(FulfillmentOrder fo){
        FulfillmentOrderLineItem foli = new FulfillmentOrderLineItem(
                                            FulfillmentOrderId = fo.Id,
                                            Quantity = 1.0,
                                            OriginalQuantity = 1.0,
                                            Type = 'Order Product',
                                            TypeCode = 'Product'
                                        );
        insert foli;
        return foli;
    }

    // Create OCI Interaction Fulfillment Order
    private static OCIInteractionFulfillOrder__c seedOCIFullfillOrder(FulfillmentOrder fo){
        OCIInteractionFulfillOrder__c ociFulfill = new OCIInteractionFulfillOrder__c(
                                                        FulfillmentOrder__c = fo.Id,
                                                        Status__c = 'REQUESTED',
                                                        Type__c = 'TRANSFER_MOVE',
                                                        ConnectionFailedAttempts__c = 0,
                                                        Schedule__c = DateTime.now()
                                                    );
        insert ociFulfill;
        return ociFulfill;    
    }
    
    // Create OCI Interaction Fulfillment Order Item
    private static OCIInteractionFulfillOrderItem__c seedOCIFullfillOrderItem(OCIInteractionFulfillOrder__c ociFulfill, FulfillmentOrderLineItem foli, String mainFulfillmentOrderItem, String associatedItemInventory){
        OCIInteractionFulfillOrderItem__c ociFulfillItem = new OCIInteractionFulfillOrderItem__c(
                                                                OCIInteractionFulfillOrder__c = ociFulfill.Id,
                                                                FulfillmentOrderItem__c = foli.Id,
                                                                Quantity__c = 1,
                                                                Status__c = 'REQUESTED',
                                                                Type__c = 'TRANSFER_MOVE',
                                                                Main_Fulfillment_Order_Item__c = mainFulfillmentOrderItem,
                                                                Associated_Item_Inventory__c = associatedItemInventory
                                                            );
        insert ociFulfillItem;
        return ociFulfillItem;
    }
}