force-app/main/default/objects/OCIInteractionFulfillOrder__c/OCIInteractionFulfillOrder__c.object-meta.xml
<CustomObject>
    <label>OCI Interaction Fulfill Order</label>
    <nameField>
        <displayFormat>OCI-F-{0000}</displayFormat>
        <label>IASInteractionFulfillOrder Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCI Interaction Fulfill Order</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OCIInteractionFulfillOrder__c/fields/ConnectionFailedAttempts__c.field-meta.xml
<CustomField>
    <fullName>ConnectionFailedAttempts__c</fullName>
    <label>Connection Failed Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrder__c/fields/FulfillmentOrder__c.field-meta.xml
<CustomField>
    <fullName>FulfillmentOrder__c</fullName>
    <label>Fulfillment Order</label>
    <referenceTo>FulfillmentOrder</referenceTo>
    <relationshipLabel>OCI Interaction Fulfill Orders</relationshipLabel>
    <relationshipName>OCIInteractionFulfillOrders</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrder__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <label>Schedule</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrder__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ABANDONED</fullName>
            </value>
            <value>
                <fullName>COMPLETED_FAIL</fullName>
            </value>
            <value>
                <fullName>COMPLETED_SUCCEED</fullName>
            </value>
            <value>
                <fullName>REQUESTED</fullName>
                <default>true</default>
                <label>REQUESTED</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrder__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TRANSFER_MOVE</fullName>
            </value>
            <value>
                <fullName>TRANSFER_CANCEL</fullName>
            </value>
            <value>
                <fullName>FULFILLMENT</fullName>
                <default>true</default>
                <label>FULFILLMENT</label>
            </value>
            <value>
                <fullName>TRANSFER_RELEASE</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/OCIInteractionFulfillOrderItem__c.object-meta.xml
<CustomObject>
    <label>OCI Interaction Fulfill Order Item</label>
    <nameField>
        <displayFormat>OCI-FI-{0000}</displayFormat>
        <label>OCIInteractionFulfillOrderItem Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCI Interaction Fulfill Order Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/fields/FulfillmentOrderItem__c.field-meta.xml
<CustomField>
    <fullName>FulfillmentOrderItem__c</fullName>
    <label>Fulfillment Order Product</label>
    <referenceTo>FulfillmentOrderLineItem</referenceTo>
    <relationshipLabel>OCI Interaction Fulfill Order Items</relationshipLabel>
    <relationshipName>OCIInteractionFulfillOrderItems</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/fields/OCIInteractionFulfillOrder__c.field-meta.xml
<CustomField>
    <fullName>OCIInteractionFulfillOrder__c</fullName>
    <label>OCI Interaction Fulfill Order</label>
    <referenceTo>OCIInteractionFulfillOrder__c</referenceTo>
    <relationshipLabel>OCI Interaction Fulfill Order Items</relationshipLabel>
    <relationshipName>OCIInteractionFulfillOrderItems</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <required>true</required>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OCIInteractionFulfillOrderItem__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REQUESTED</fullName>
                <default>true</default>
                <label>REQUESTED</label>
            </value>
            <value>
                <fullName>COMPLETED_SUCCEED</fullName>
            </value>
            <value>
                <fullName>COMPLETED_FAIL</fullName>
            </value>
            <value>
                <fullName>ABANDONED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/UpdateOCIInteractionFulfillOrderTest.cls
@isTest
private class UpdateOCIInteractionFulfillOrderTest {
    @isTest static void test_UpdateOCIInteractionFulfillOrderTrigger() {
        
        // Create Records
        FulfillmentOrder fo = seedFulfillOrder();
        FulfillmentOrderLineItem foli = seedFulfillOrderLineItem(fo);
        OCIInteractionFulfillOrder__c ociFulfill = seedOCIFullfillOrder(fo);
        OCIInteractionFulfillOrderItem__c ociFulfillItem = seedOCIFullfillOrderItem(ociFulfill, foli);

        System.Test.startTest();
        ociFulfill.Status__c = 'ABANDONED';
        ociFulfill.Type__c = 'TRANSFER_CANCEL';
        update ociFulfill;

        System.Test.stopTest();

        OCIInteractionFulfillOrderItem__c audit = [SELECT Id, Status__c, Type__c FROM OCIInteractionFulfillOrderItem__c WHERE OCIInteractionFulfillOrder__c = : ociFulfill.Id LIMIT 1];
        System.assertEquals(ociFulfillItem.Id, audit.Id);
        System.assertEquals('ABANDONED', audit.Status__c);
        System.assertEquals('TRANSFER_CANCEL', audit.Type__c);       
    }


    // Create Fulfillment Order
    private static FulfillmentOrder seedFulfillOrder(){
        OrderDeliveryMethod odm = new OrderDeliveryMethod(
                                        IsActive = false,
                                        Name = 'test'
                                    );
        insert odm;
        FulfillmentOrder fo = new FulfillmentOrder(
                                    status = 'Draft',
                                    FulfilledToName = 'test',
                                    DeliveryMethodId = odm.Id
                                );
        insert fo;
        return fo;
    }

    // Create Fulfillment Order Line Item
    private static FulfillmentOrderLineItem seedFulfillOrderLineItem(FulfillmentOrder fo){
        FulfillmentOrderLineItem foli = new FulfillmentOrderLineItem(
                                            FulfillmentOrderId = fo.Id,
                                            Quantity = 1.0,
                                            OriginalQuantity = 1.0,
                                            Type = 'Order Product',
                                            TypeCode = 'Product'
                                        );
        insert foli;
        return foli;
    }

    // Create OCI Interaction Fulfillment Order
    private static OCIInteractionFulfillOrder__c seedOCIFullfillOrder(FulfillmentOrder fo){
        OCIInteractionFulfillOrder__c ociFulfill = new OCIInteractionFulfillOrder__c(
                                                        FulfillmentOrder__c = fo.Id,
                                                        Status__c = 'REQUESTED',
                                                        Type__c = 'TRANSFER_MOVE',
                                                        ConnectionFailedAttempts__c = 0,
                                                        Schedule__c = DateTime.now()
                                                    );
        insert ociFulfill;
        return ociFulfill;    
    }
    
    // Create OCI Interaction Fulfillment Order Item
    private static OCIInteractionFulfillOrderItem__c seedOCIFullfillOrderItem(OCIInteractionFulfillOrder__c ociFulfill, FulfillmentOrderLineItem foli){
        OCIInteractionFulfillOrderItem__c ociFulfillItem = new OCIInteractionFulfillOrderItem__c(
                                                                OCIInteractionFulfillOrder__c = ociFulfill.Id,
                                                                FulfillmentOrderItem__c = foli.Id,
                                                                Quantity__c = 1,
                                                                Status__c = 'REQUESTED',
                                                                Type__c = 'TRANSFER_MOVE'
                                                            );
        insert ociFulfillItem;
        return ociFulfillItem;
    }
    
}