force-app/main/default/objects/OCIInteractionOrderItemSummary__c/OCIInteractionOrderItemSummary__c.object-meta.xml
<CustomObject>
    <label>OCI Interaction Order Item Summary</label>
    <nameField>
        <displayFormat>OCI-{0000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCI Interaction Order Item Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OCIInteractionOrderItemSummary__c/fields/Associated_Item_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Associated_Item_Inventory__c</fullName>
    <label>Associated Item Inventory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IncludedInMainInventory</fullName>
            </value>
            <value>
                <fullName>NotIncludedInMainInventory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OCIInteractionOrderItemSummary__c/fields/Main_Order_Item_Summary__c.field-meta.xml
<CustomField>
    <fullName>Main_Order_Item_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Order Item Summary</label>
    <referenceTo>OrderItemSummary</referenceTo>
    <relationshipLabel>OCI Interaction Order Item Summaries (Main Order Item Summary)</relationshipLabel>
    <relationshipName>OCI_Interaction_Order_Item_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OCIInteractionOrderItemSummary__c/fields/OCIInteractionOrderSummary__c.field-meta.xml
<CustomField>
    <fullName>OCIInteractionOrderSummary__c</fullName>
    <label>OCI Interaction Order Summary</label>
    <referenceTo>OCIInteractionOrderSummary__c</referenceTo>
    <relationshipLabel>OCI Interaction Order Item Summaries</relationshipLabel>
    <relationshipName>OCIInteractionOrderItemSummaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OCIInteractionOrderItemSummary__c/fields/OrderItemSummary__c.field-meta.xml
<CustomField>
    <fullName>OrderItemSummary__c</fullName>
    <label>Order Product Summary</label>
    <referenceTo>OrderItemSummary</referenceTo>
    <relationshipLabel>OCI Interaction Order Item Summaries</relationshipLabel>
    <relationshipName>OCIInteractionOrderItemSummaries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OCIInteractionOrderItemSummary__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>REQUESTED</fullName>
                <default>true</default>
                <label>REQUESTED</label>
            </value>
            <value>
                <fullName>COMPLETED_SUCCEED</fullName>
            </value>
            <value>
                <fullName>COMPLETED_FAIL</fullName>
            </value>
            <value>
                <fullName>ABANDONED</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OCIInteractionOrderItemSummary__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>TRANSFER_ROUTING</fullName>
                <default>true</default>
                <label>TRANSFER_ROUTING</label>
            </value>
            <value>
                <fullName>RELEASE</fullName>
            </value>
            <value>
                <fullName>TRANSFER_MOVING</fullName>
            </value>
            <value>
                <fullName>CREATE_RESERVATION</fullName>
            </value>
            <value>
                <fullName>RELEASE_RESERVATION</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OCIInteractionOrderSummary__c/OCIInteractionOrderSummary__c.object-meta.xml
<CustomObject>
    <label>OCI Interaction Order Summary</label>
    <nameField>
        <displayFormat>OCI-{0000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCI Interaction Order Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OCIInteractionOrderSummary__c/fields/ConnectionFailAttempts__c.field-meta.xml
<CustomField>
    <fullName>ConnectionFailAttempts__c</fullName>
    <label>Connection Fail Attempts</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/OCIInteractionOrderSummary__c/fields/OrderDeliveryGroupSummary__c.field-meta.xml
<CustomField>
    <fullName>OrderDeliveryGroupSummary__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Order Delivery Group Summary</label>
    <referenceTo>OrderDeliveryGroupSummary</referenceTo>
    <relationshipLabel>OCI Interaction Order Delivery Group Summaries</relationshipLabel>
    <relationshipName>OCIInteractioOrderDeliveryGrpSummaries</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OCIInteractionOrderSummary__c/fields/OrderSummary__c.field-meta.xml
<CustomField>
    <fullName>OrderSummary__c</fullName>
    <label>Order Summary</label>
    <referenceTo>OrderSummary</referenceTo>
    <relationshipLabel>OCI Interactions Order Summaries</relationshipLabel>
    <relationshipName>OCIInteractionsOrderSummaries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/OCIInteractionOrderSummary__c/fields/Schedule__c.field-meta.xml
<CustomField>
    <fullName>Schedule__c</fullName>
    <defaultValue>NOW()</defaultValue>
    <label>Schedule</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

force-app/main/default/classes/OCIInteractionOISBundleActionTest.cls
@IsTest(SeeAllData=true)
private class OCIInteractionOISBundleActionTest {

    @isTest
    static void testRegularProducts() {
        // Assign
        List<OCIInteractionOISBundleActionInput> inputs = new List<OCIInteractionOISBundleActionInput>();
        OCIInteractionOISBundleActionInput input = new OCIInteractionOISBundleActionInput();

        input.ociInteractionOrderItemSummaries = CreateOCIInteractionItemSummariesWithRegularProducts();
        inputs.add(input);

        // Action
        List<OCIInteractionOISBundleActionOutput> outputs = OCIInteractionOISBundleAction.getOCIInteractionOrderItemSummaryRecordsWithInventory(inputs);

        // Assert
        System.assert(outputs != null, 'bundleActionOutput should not be null');
        System.assert(outputs[0].OCIInteractionItemSummariesWithInventory != null, 'bundleActionOutput.ociInteractionItemSummariesWithInventory should not be null');
        System.assert(outputs[0].OCIInteractionItemSummariesWithInventory.size() == 3);
        System.assert(inputs[0].OCIInteractionOrderItemSummaries.size() == 3);
    }
    
    @isTest
    static void testBundleAndInventoryAtParent() {
        // Assign
        List<OCIInteractionOISBundleActionInput> inputs = new List<OCIInteractionOISBundleActionInput>();
        OCIInteractionOISBundleActionInput input = new OCIInteractionOISBundleActionInput();

        input.ociInteractionOrderItemSummaries = CreateOCIInteractionItemSummariesAndInventoryAtParent(false);
        inputs.add(input);
        
        // Action
        List<OCIInteractionOISBundleActionOutput> outputs = OCIInteractionOISBundleAction.getOCIInteractionOrderItemSummaryRecordsWithInventory(inputs);

        // Assert
        System.assert(outputs != null, 'bundleActionOutput should not be null');
        System.assert(outputs[0].OCIInteractionItemSummariesWithInventory != null, 'bundleActionOutput.ociInteractionItemSummariesWithInventory should not be null');
        System.assert(outputs[0].OCIInteractionItemSummariesWithInventory.size() == 1);
        System.assert(inputs[0].OCIInteractionOrderItemSummaries.size() == 3);
        
        List<String> childrenIds = new List<String>();
        childrenIds.add(input.ociInteractionOrderItemSummaries[1].Id);
        childrenIds.add(input.ociInteractionOrderItemSummaries[2].Id);
        
        // Check there is no child items from output
        for(OCIInteractionOrderItemSummary__c oiois: outputs[0].ociInteractionItemSummariesWithInventory){
            System.assert(!childrenIds.contains(oiois.Id));
        }
    }

    @isTest
    static void testBundleAndInventoryAtParentAndNullStockCheckMethod() {
        // Assign
        List<OCIInteractionOISBundleActionInput> inputs = new List<OCIInteractionOISBundleActionInput>();
        OCIInteractionOISBundleActionInput input = new OCIInteractionOISBundleActionInput();

        input.ociInteractionOrderItemSummaries = CreateOCIInteractionItemSummariesAndInventoryAtParent(true);
        inputs.add(input);
        
        // Action
        List<OCIInteractionOISBundleActionOutput> outputs = OCIInteractionOISBundleAction.getOCIInteractionOrderItemSummaryRecordsWithInventory(inputs);

        // Assert
        System.assert(outputs != null, 'bundleActionOutput should not be null');
        System.assert(outputs[0].OCIInteractionItemSummariesWithInventory != null, 'bundleActionOutput.ociInteractionItemSummariesWithInventory should not be null');
        System.assert(outputs[0].OCIInteractionItemSummariesWithInventory.size() == 1);
        System.assert(inputs[0].OCIInteractionOrderItemSummaries.size() == 3);
        
        List<String> childrenIds = new List<String>();
        childrenIds.add(input.ociInteractionOrderItemSummaries[1].Id);
        childrenIds.add(input.ociInteractionOrderItemSummaries[2].Id);
        
        // Check there is no child items from output
        for(OCIInteractionOrderItemSummary__c oiois: outputs[0].ociInteractionItemSummariesWithInventory){
            System.assert(!childrenIds.contains(oiois.Id));
        }
    }
    
    @isTest
    static void testBundleAndInventoryAtChildren() {
        // Assign
        List<OCIInteractionOISBundleActionInput> inputs = new List<OCIInteractionOISBundleActionInput>();
        OCIInteractionOISBundleActionInput input = new OCIInteractionOISBundleActionInput();

        input.ociInteractionOrderItemSummaries = CreateOCIInteractionItemSummariesAndInventoryAtChildren();
        inputs.add(input);
        
        // Action
        List<OCIInteractionOISBundleActionOutput> outputs = OCIInteractionOISBundleAction.getOCIInteractionOrderItemSummaryRecordsWithInventory(inputs);

        // Assert        
        System.assert(outputs != null, 'bundleActionOutput should not be null');
        System.assert(outputs[0].OCIInteractionItemSummariesWithInventory != null, 'bundleActionOutput.ociInteractionItemSummariesWithInventory should not be null');
        System.assert(outputs[0].OCIInteractionItemSummariesWithInventory.size() == 2);
        System.assert(inputs[0].OCIInteractionOrderItemSummaries.size() == 3);
        
        List<String> parentIds = new List<String>();
        parentIds.add(input.ociInteractionOrderItemSummaries[0].Id);
        
        // Check there is no parent items from output
        for(OCIInteractionOrderItemSummary__c oiois: outputs[0].ociInteractionItemSummariesWithInventory){
            System.assert(!parentIds.contains(oiois.Id));
        }
    }
    
    private static List<OCIInteractionOrderItemSummary__c> CreateOCIInteractionItemSummariesWithRegularProducts(){
        String orderSummaryId = CreateOrderSummary();
        List<OrderItemSummary> orderItemSummaries = TestDataGenerator.getOrderItemSummaries(orderSummaryId);
  
        OCIInteractionOrderSummary__c ociInteractionOrderSummary = CreateOCIInteractionOrderSummary(orderSummaryId, orderItemSummaries[0].OrderDeliveryGroupSummaryId);
       
        List<OCIInteractionOrderItemSummary__c> ociInteractionOrderItemSummaries = new List<OCIInteractionOrderItemSummary__c>();
        
        OCIInteractionOrderItemSummary__c item1 = CreateOCIInteractionOrderItemSummary(ociInteractionOrderSummary.Id, orderItemSummaries[0].Id, null, null);
        OCIInteractionOrderItemSummary__c item2 = CreateOCIInteractionOrderItemSummary(ociInteractionOrderSummary.Id, orderItemSummaries[1].Id, null, null);
        OCIInteractionOrderItemSummary__c item3 = CreateOCIInteractionOrderItemSummary(ociInteractionOrderSummary.Id, orderItemSummaries[2].Id, null, null);
        
        ociInteractionOrderItemSummaries.add(item1);
        ociInteractionOrderItemSummaries.add(item2);
        ociInteractionOrderItemSummaries.add(item3);
        
        return ociInteractionOrderItemSummaries;
    }
    
    private static List<OCIInteractionOrderItemSummary__c> CreateOCIInteractionItemSummariesAndInventoryAtChildren(){
        String orderSummaryId = CreateOrderSummary();
        List<OrderItemSummary> orderItemSummaries = TestDataGenerator.getOrderItemSummaries(orderSummaryId);
  
        OCIInteractionOrderSummary__c ociInteractionOrderSummary = CreateOCIInteractionOrderSummary(orderSummaryId, orderItemSummaries[0].OrderDeliveryGroupSummaryId);
       
        List<OCIInteractionOrderItemSummary__c> ociInteractionOrderItemSummaries = new List<OCIInteractionOrderItemSummary__c>();
        
        OCIInteractionOrderItemSummary__c item1 = CreateOCIInteractionOrderItemSummary(ociInteractionOrderSummary.Id, orderItemSummaries[0].Id, null, null);
        OCIInteractionOrderItemSummary__c item1_1 = CreateOCIInteractionOrderItemSummary(ociInteractionOrderSummary.Id, orderItemSummaries[1].Id, 'NotIncludedInMainInventory', orderItemSummaries[0].Id);
        OCIInteractionOrderItemSummary__c item1_2 = CreateOCIInteractionOrderItemSummary(ociInteractionOrderSummary.Id, orderItemSummaries[2].Id, 'NotIncludedInMainInventory', orderItemSummaries[0].Id);
        
        ociInteractionOrderItemSummaries.add(item1);
        ociInteractionOrderItemSummaries.add(item1_1);
        ociInteractionOrderItemSummaries.add(item1_2);
        
        return ociInteractionOrderItemSummaries;
    }
    
    private static List<OCIInteractionOrderItemSummary__c> CreateOCIInteractionItemSummariesAndInventoryAtParent(Boolean nullStockCheckMethod){
        String orderSummaryId = CreateOrderSummary();
        List<OrderItemSummary> orderItemSummaries = TestDataGenerator.getOrderItemSummaries(orderSummaryId);

        OCIInteractionOrderSummary__c ociInteractionOrderSummary = CreateOCIInteractionOrderSummary(orderSummaryId, orderItemSummaries[0].OrderDeliveryGroupSummaryId);
       
        List<OCIInteractionOrderItemSummary__c> ociInteractionOrderItemSummaries = new List<OCIInteractionOrderItemSummary__c>();
        
        OCIInteractionOrderItemSummary__c item1 = CreateOCIInteractionOrderItemSummary(ociInteractionOrderSummary.Id, orderItemSummaries[0].Id, null, null);
        OCIInteractionOrderItemSummary__c item1_1 = CreateOCIInteractionOrderItemSummary(ociInteractionOrderSummary.Id, orderItemSummaries[1].Id, nullStockCheckMethod ? null : 'IncludedInMainInventory', orderItemSummaries[0].Id);
        OCIInteractionOrderItemSummary__c item1_2 = CreateOCIInteractionOrderItemSummary(ociInteractionOrderSummary.Id, orderItemSummaries[2].Id, nullStockCheckMethod ? null : 'IncludedInMainInventory', orderItemSummaries[0].Id);
        
        ociInteractionOrderItemSummaries.add(item1);
        ociInteractionOrderItemSummaries.add(item1_1);
        ociInteractionOrderItemSummaries.add(item1_2);
        
        return ociInteractionOrderItemSummaries;
    }
    
    private static OCIInteractionOrderSummary__c CreateOCIInteractionOrderSummary(String orderSummaryId, String orderDeliveryGroupSummaryId){
        OCIInteractionOrderSummary__c oios = new OCIInteractionOrderSummary__c();
        
        oios.OrderSummary__c = orderSummaryId;
        oios.Status__c = 'REQUESTED';
        oios.Type__c = 'TRANSFER_ROUTING';
        oios.ConnectionFailAttempts__c = 0;
        oios.OrderDeliveryGroupSummary__c = orderDeliveryGroupSummaryId;
        oios.Schedule__c = DateTime.now();
        insert oios;
        return oios;
    }

    private static OCIInteractionOrderItemSummary__c CreateOCIInteractionOrderItemSummary(Id OCIInteractionOrderSummaryId, 
    Id OrderItemSummaryId, String associatedItemInventory, Id mainOrderItemSummary){
        OCIInteractionOrderItemSummary__c oiois = new OCIInteractionOrderItemSummary__c();
        
        oiois.OCIInteractionOrderSummary__c = OCIInteractionOrderSummaryId;
        oiois.OrderItemSummary__c = OrderItemSummaryId;
        oiois.Status__c = 'REQUESTED';
        oiois.Type__c = 'TRANSFER_ROUTING';
        oiois.Quantity__c = 1;
        oiois.Associated_Item_Inventory__c = associatedItemInventory;
        oiois.Main_Order_Item_Summary__c = mainOrderItemSummary;
        
        insert oiois;
        return oiois;
    }
    
    private static String CreateOrderSummary() {
        String timestamp = String.valueOf(DateTime.now());
        List<OrderItem> orderItems = TestDataGenerator.createOrderAndOrderItems(timestamp);
        Order order = [SELECT Id, Status FROM Order WHERE Id =: orderItems[0].OrderId];
        order.Status='Activated';
        update order;
        return TestDataGenerator.createOrderSummary(order.Id);
    }
    
}