force-app/main/default/objects/OCIInteractionOrderItemSummary__c/OCIInteractionOrderItemSummary__c.object-meta.xml
<CustomObject>
    <label>OCI Interaction Order Item Summary</label>
    <nameField>
        <displayFormat>OCI-{0000}</displayFormat>
        <label>Interaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OCI Interaction Order Item Summaries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/OCIInteractionOrderItemSummary__c/fields/Associated_Item_Inventory__c.field-meta.xml
<CustomField>
    <fullName>Associated_Item_Inventory__c</fullName>
    <label>Associated Item Inventory</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>IncludedInMainInventory</fullName>
            </value>
            <value>
                <fullName>NotIncludedInMainInventory</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/OCIInteractionOrderItemSummary__c/fields/Main_Order_Item_Summary__c.field-meta.xml
<CustomField>
    <fullName>Main_Order_Item_Summary__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Main Order Item Summary</label>
    <referenceTo>OrderItemSummary</referenceTo>
    <relationshipLabel>OCI Interaction Order Item Summaries (Main Order Item Summary)</relationshipLabel>
    <relationshipName>OCI_Interaction_Order_Item_Summaries</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/OCIInteractionOrderItemSummary__c/fields/OrderItemSummary__c.field-meta.xml
<CustomField>
    <fullName>OrderItemSummary__c</fullName>
    <label>Order Product Summary</label>
    <referenceTo>OrderItemSummary</referenceTo>
    <relationshipLabel>OCI Interaction Order Item Summaries</relationshipLabel>
    <relationshipName>OCIInteractionOrderItemSummaries</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/classes/OCIInteractionOISBundleAction.cls
public with sharing class OCIInteractionOISBundleAction {

    public OCIInteractionOISBundleAction() {

    }

    @InvocableMethod(label='Get OCI Interaction Order Item Summaries with inventory' description='Extracts OCI Interaction Order Item Summaries with inventory' category='Order Management')
    public static List<OCIInteractionOISBundleActionOutput> getOCIInteractionOrderItemSummaryRecordsWithInventory(List<OCIInteractionOISBundleActionInput> inputs){

        List<OCIInteractionOISBundleActionOutput> results = new List<OCIInteractionOISBundleActionOutput>();

        for (OCIInteractionOISBundleActionInput input : inputs) {
        
            OCIInteractionOISBundleActionOutput output = new OCIInteractionOISBundleActionOutput();
            
            Set<String> parentsWithoutInventory = new Set<String>();
            
            List<OCIInteractionOrderItemSummary__c> remainingItemsToProcess = new List<OCIInteractionOrderItemSummary__c>();
            
            for (OCIInteractionOrderItemSummary__c item: input.ociInteractionOrderItemSummaries) {
                // all children
                if (item.Main_Order_Item_Summary__c != null) {
                    // children with inventory
                    if (item.Associated_Item_Inventory__c == 'NotIncludedInMainInventory') {
                        output.OCIInteractionItemSummariesWithInventory.add(item);
                        // parents without inventory
                        if (!parentsWithoutInventory.contains(item.Main_Order_Item_Summary__c)) {
                            parentsWithoutInventory.add(item.Main_Order_Item_Summary__c);
                        }
                    }
                // all parents + non bundles 
                } else {
                    remainingItemsToProcess.add(item);
                }
            }
        
            if (parentsWithoutInventory.size() == 0) {
                output.OCIInteractionItemSummariesWithInventory.addAll(remainingItemsToProcess);
            } else {
                for (OCIInteractionOrderItemSummary__c item: remainingItemsToProcess) {
                    if (!parentsWithoutInventory.contains(item.OrderItemSummary__c)) {
                        output.OCIInteractionItemSummariesWithInventory.add(item);
                    }
                }
            }
            results.add(output);
        }
        return results;
    }
}